### ISSUE TITLE
Bukkit.getOnlinePlayers().size() -> .length()

### ISSUE THREAD

**Issue by Shadow48402** [Hidendra/Plugin-Metrics#61]
Rule 335 of the Metrics class for Bukkit.

**Comment by Ribesg** [comment]
Should be closed by https://github.com/Hidendra/Plugin-Metrics/commit/e59b7c2477bf3c1ec513fed53fd1c007eee77602.

**Comment by Hidendra** [comment]
Indeed, thanks
