### ISSUE TITLE
.size() error with 1.8

### ISSUE THREAD

**Issue by metmad22** [Hidendra/Plugin-Metrics#62]
Hello there, I tried adding metrics to my plugin, but my IDE is giving me an error. Here it is.

http://puu.sh/eRuix/63ecf6d242.png

It will not understand what .size() is. I tried .length() as well. Nothing.

Thank you.

**Comment by tmfksoft** [comment]
Hi metmadd22, I just encountered the same issue.
Just change .size() to .length

As so:
int playersOnline = Bukkit.getServer().getOnlinePlayers().length;

Seems to fix it!

**Comment by metmad22** [comment]
I've tried already. It gives me the same error. "Cannot find symbol"

**Comment by Ribesg** [comment]
Should be closed by https://github.com/Hidendra/Plugin-Metrics/commit/e59b7c2477bf3c1ec513fed53fd1c007eee77602.

**Comment by Hidendra** [comment]
Indeed, thanks
