### ISSUE TITLE
Forge: isOptOut called on every tick, reloads config file on every tick

### ISSUE THREAD

**Issue by nallar** [Hidendra/Plugin-Metrics#73]
https://github.com/Hidendra/Plugin-Metrics/blob/master/mods/forge/metrics/src/main/java/org/mcstats/Metrics.java#L193

isOptOut is called on every tick, resulting in a slow call to configuration.load().

This could be fixed by moving the isOptOut call after the interval check.

I don't get why isOptOut needs to be called repeatedly. Is it required to support opting out by editing the config file while the server is running?

**Comment by Minecrell** [comment]
It's supposed to check if the user has opted-out in the meantime before attempting to contact MCStats. However, for that it would be enough to do that when that thread is started, so once every 15 minutes, not 20 times a second.
